//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiKErnel.Performance.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiKErnel.Performance.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.03589149106084682,0.07133613831134915,0.0391358938887322,0.03937981372592755,0.047005885942737684,0.02604131688212322,0.031198587312000443,0.0822156617113433,0.10948391113063705,0.01103132718151042,0.10135345110092654,0.016574526565081238,0.02915262047449746,0.15300858031975267,0.1661393012814578,0.1084913150454313,0.08910764042558231,0.06452680449362595,0.051239065961788136,0.06119012044871472,0.06617480262688154,0.07952212821502058,0.027103349662706624,0.07126918252955025,0.0719023396960447,0.0167837532 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hm0_12h {
            get {
                return ResourceManager.GetString("Hm0_12h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9.1792831,9. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htime_12h {
            get {
                return ResourceManager.GetString("htime_12h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.7709076155197593,1.0547968683618865,0.7991830517310242,0.8037987440622532,0.8734942894430808,0.6782566054799141,0.7223869419372067,1.3053089342434037,1.4978110513593996,0.31051974753006495,1.3169132822988108,0.4635788573813818,0.7079657353716066,1.7403215846187277,1.8258162806525555,1.5126655027858178,1.3683873922280416,1.0556234486271248,0.9456514272483849,1.109140247080258,1.0231437961021026,1.1681598845039745,0.6832391714644149,1.111424737893438,1.0486659169723083,0.45241566937185146,0.1739191668136679 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tmm10_12h {
            get {
                return ResourceManager.GetString("Tmm10_12h", resourceCulture);
            }
        }
    }
}
